### ISSUE TITLE
Apply a default label to new issues

### ISSUE THREAD

**Issue by paoloantinori** [redhat-ipaas/pure-bot#36]
Currently required to apply Triage label.

**Comment by zregvart** [comment]
I can take a look at this if no one is atm.

**Comment by gashcrumb** [comment]
The previous issue was assigned to @rhuss but I'll let you guys duke it out :-)

**Comment by zregvart** [comment]
![won](https://user-images.githubusercontent.com/1306050/37525739-ecd42736-292d-11e8-9d47-51c7202e6f66.gif)

**Comment by zregvart** [comment]
Done.

**Comment by paoloantinori** [comment]
cool, i see this is already in place! thank you!
