### ISSUE TITLE
purebot require reviews from *all* reviewers instead of just one

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/pure-bot#39]
Seems like approved PRs are stacking up, after looking at a couple that had been sitting with an `approved` label for hours I found that while the PR had been approved by someone, the person who opened the PR requested reviews from multiple people, and so apparently it's now required that everyone marked as a reviewer needs to approve the changes.

Is this by design?

**Comment by rhuss** [comment]
No, shouldn't be.IMO a single approval (which is hard to get anyway ;-) should be enough.

I'm going to check this tomorrow ....

**Comment by gashcrumb** [comment]
Awesome thanks!  2 prs were in this state so figured it might be a
problem....

**Comment by rhuss** [comment]
@gashcrumb @deeleman  Actually the algorithm is like this:

* If no reviewers requested the 'wip' check always passes
* If reviewers are requested:
  - If **one** of the _requested_ reviewers approved then check passes, too.
  - If not a single reviewer approved, then the check **fails**

https://github.com/syndesisio/pure-bot/blob/fe70ea7dbbafe4100bdbe67e1c0c1defe0b44069/pkg/webhook/utils.go#L106-L113

So its not the case that everyone has to approve, a single one is enough. Not sure why it didn't work for https://github.com/syndesisio/syndesis/pull/2085. Have to dig deeper.

**Comment by rhuss** [comment]
Think I found it: That check only runs on a state change of the PR itself (e.g. when opened, reopened, labeled, unlabeled, edited, synchronize). But if someone approves it, that doesn't trigger a state change.

This theory can be easily verified by just adding an (arbitrary) label to an approved PR. @gashcrumb do you have a pending, open PR just handy ?

**Comment by gashcrumb** [comment]
Not currently.  So in the case of multiple reviewers, one person approves, which somehow triggers having the 'approved' label added, I guess that would then be a state change that *could* trigger a WIP check maybe?

**Comment by rhuss** [comment]
yep, actually yes. However I would find it much better to add this kind of check directly to a PullRequestReview event, which also gets fired.

I'm going to play around with this on our test project for a moment.
