### ISSUE TITLE
Bot seems to be reopening issues

### ISSUE THREAD

**Issue by zregvart** [redhat-ipaas/pure-bot#51]
Examples:
https://github.com/syndesisio/syndesis/issues/3675
https://github.com/syndesisio/syndesis/issues/3674

**Comment by gashcrumb** [comment]
And [this question](https://github.com/syndesisio/syndesis/issues/3672#issuecomment-424773461) :-) 

> @heiko-braun wonder, I autoclosed this issue with a PR and it's reopened with the done label there, does that mean this should be tested by QE before actually being closed? I thought only QE raised issues really needed to be handled in this way...

Mostly wondering if we'll eventually wind up with many open issues with done labels that eventually only get closed because they get detected as stale :-)

**Comment by heiko-braun** [comment]
Yes, it happens intentionally to be able to insert a step in the workflow that prompts verification. The idea would be to close issues  (moving from `done` to `closed`) at the end of each sprint.

In addition (currently missing) I planned to add different closed states, i.e. `closed/verified`, `closed/stale`, etc

I am happy to discuss this further if you think it's getting in your way.

**Comment by gashcrumb** [comment]
I think that's fine.  So maybe we should just leave these issues as-is tagged with 'done' as then it's easy enough to just filter and close them en masse on the last day of the sprint...

**Comment by heiko-braun** [comment]
Yes, that's the idea. All changes have been made to tell apart what we did at the end of a sprint. One single `closed` bucket doesn't allow me to differentiate.

**Comment by zregvart** [comment]
Not closing issues though is making me hard to find what I need to do next if I go by open issues assigned to me. I would prefer a workflow where issues are re-opened  only if the human chooses to re-open it as a regression.
Surely we can track what we need to track via labels or zenhub board column?

**Comment by zregvart** [comment]
I also get new notifications which kinda sucks.
