### ISSUE TITLE
status/wip check is not working

### ISSUE THREAD

**Issue by igarashitm** [redhat-ipaas/pure-bot#53]
Seems it's not working on https://github.com/atlasmap/atlasmap
![screenshot from 2018-10-05 08-58-14](https://user-images.githubusercontent.com/265462/46537017-37a82100-c87e-11e8-85f3-dc97fa997ecf.png)

**Comment by rhuss** [comment]
@igarashitm We configure the label "pr/wip" for holding back merged, not "status/wip".

Does this help ?

**Comment by igarashitm** [comment]
Oh OK let me try - I actually grepped in source code and found `status/wip` and `wip`, so I though something wrong is happening.

**Comment by igarashitm** [comment]
OK worked with `pr/wip` - closing.
