### ISSUE TITLE
Rename to Cindy

### ISSUE THREAD

**Issue by zregvart** [redhat-ipaas/pure-bot#65]
Sounds like the first syllable of "Syndesis", kinda.

https://www.urbandictionary.com/define.php?term=Cindy

**Comment by rhuss** [comment]
Yeah, it's kinda hard to follow pure-bot when it sometimes works and sometimes not. E.g. the last failure was due to a missing nil-check, which can be found out by looking into the logs of the pure-bot Pod.

But yeah, happy if someone want to rename it ;-)
